### ISSUE TITLE
Feature Proposal: Add boolean operator and TryGet method

### ISSUE THREAD

**Issue by Paxol** [marcominerva/OperationResults#44]
It would be nice to add a bool implicit conversion that checks if the result is successful and a TryGet method that uses the out keyword to extract the content of a Result object.

I took the inspiration from the Result object in DotNext package (https://github.com/dotnet/dotNext/blob/gh-pages/src/DotNext/Result.cs).

I would like to contribute on this.

**Comment by marcominerva** [comment]
Thanks for the suggestion @Paxol!

Feel free to make a Pull Request with your idea (remember to make it in the **develop** branch), I will be happy to check it out.
